spring.application.name=ciphervault
server.address=0.0.0.0
server.port=8080
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration

